import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { AptosProvider } from "@/components/AptosWalletProvider";
import { Nerko_One } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const nerko = Nerko_One({ 
  weight: "400",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AptosProvider>
        <body className={`${inter.className} ${nerko.className} dark`}>{children}</body>
      </AptosProvider>
    </html>
  );
}
